import numpy as np


a = [1,2,3,4,5]
arr = np.array(a)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print('1===========================')
arr = np.arange(1,26).reshape(5,5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print('2===========================')
arr = np.random.randint(10,99,size=(2,6))
print(arr)
arr = arr.reshape(4,3)
print(arr)
arr = np.resize(arr,new_shape=(2,2))
print(arr)
print('3===========================')
arr = np.linspace(0,5,num=10)
print(arr)
print('4===========================')
arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr*2)
print(arr<4)
newarr = arr[arr<4]
print(newarr)
newarr = arr[(arr<4) & (arr%2==0)]
print(newarr)
newarr = arr[(arr<7) | (arr%2==0)]
print(newarr)
print('5===========================')
print(arr)
print(arr[1,2])
print(arr[1])
print(arr[:,1])
print(arr[1:, 0:2])
print('6===========================')
print(arr)
print(np.mean(arr, axis=1))
print('7===========================')
print(arr)
arr = np.delete(arr, 1, axis=0)
print(arr)
arr = np.insert(arr, 1, values=[0,0,0], axis=0)
print(arr)
print('8===========================')
arr = np.random.randint(1, 1000, 50)
print(arr)
arr = arr.reshape(5, 10)
print(arr)
arr = arr.reshape(10, 5)
print(arr)
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.max(axis=1))
print(arr.min(axis=1))
print(arr.mean(axis=1))


arr = np.random.randint(1, 100, size=(4, 4))
print(np.mean(arr, axis=0))  # среднее в столбиках
a = np.mean(arr, axis=0)  # среднее в столбиках
b = np.mean(arr, axis=1).reshape(4, 1)  # среднее в строках